version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "07:00"
      timezone: "Europe/London"
    labels:
      - "automation"
      - "github-action"
    commit-message:
      prefix: "chore(github-actions)"
    groups:
      all-github-actions:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/"
      - "/examples/minimal"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "07:00"
      timezone: "Europe/London"
    groups:
      terraform-all:
        patterns:
          - "*"
    labels:
      - "automation"
      - "terraform"
    commit-message:
      prefix: "chore(terraform)"
