name: Security

on:
  push:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  checkov:
    name: checkov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@59b9d7edfcad5b87fbe3f473a9a134a721ad03f8 # v12.3119.0
        with:
          config_file: "./configs/checkov.yml"
          directory: "."
