name: Security

on:
  push:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  checkov:
    name: checkov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@a8664e3a0549367977f0cda990a34311835c87c0 # v12.3123.0
        with:
          config_file: "./configs/checkov.yml"
          directory: "."
